### PR TITLE
suggested changes to allow retrieving measurement log-likelihood from UKF

### PR DESCRIPTION
**Pull request by williamkreamer**

### CODE REVIEW

**Comment by williamkreamer** [comment]
@rlabbe hi Roger. I'd like to retrieve the measurement log-likelihood from the UKF after each update. I'm not certain I implemented it correctly. If you have time to check it and comment, I would appreciate it.

Thanks for creating this very useful package!

**Comment by rlabbe** [comment]
Hi William, thanks for this. I've been on vacation; I'll have time to look at it in the next day or two.

**Comment by williamkreamer** [comment]
cool, thanks. I see this is related to https://github.com/rlabbe/filterpy/issues/19

**Comment by peter-moran** [comment]
Any updates? Would love this, especially for use with MMAE.

**Comment by peter-moran** [comment]
Hey all, I've been trying to implement this myself. 

## Problem with pull request
@williamkreamer, I could not get your changes to work after I locally merged it with master. Specifically, `Pxz` and `Pz` are different size covariance matrices. `Pxz` is the "cross covariance of the state and the measurements" and is square with length `dim_x`, while `Pz` is the "covariance of the measurement sigma points" and is square with length `dim_z` [[1]](http://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/10-Unscented-Kalman-Filter.ipynb#Update-Step). They can't be added together and I get an error for trying to do so.

Using the residual does seem like the way forward, however.

## Attempted solution
In the linear kalman filter (`kalman_filter.py`), likelihood is calculated by:

    S = dot3(H, P, H.T) + R
    [... x and P get updated ... ]
    mean = np.array(dot(H, x)).flatten()
    flatz = np.asarray(z).flatten()    
    log_likelihood = multivariate_normal.logpdf(flatz, mean, cov=S, allow_singular=True)

If I understand correctly, in the UKF `Pz` is the equivalent of `S`, eg the covariance of the predicted state transformed into the measurement state plus the measurement noise. So I tried the code below:

    # compute log likelihood
    flaty = np.asarray(self.y)
    zero = np.zeros(len(self.y))
    self.log_likelihood = multivariate_normal.logpdf(x=flaty, mean=zero, cov=Pz, allow_singular=True)

## Still some problems
**This kind of works**, but for the first two updates I get the following error:
```
  File "/home/rp-gts/filterpy/filterpy/kalman/UKF.py", line 355, in update
    self.log_likelihood = multivariate_normal.logpdf(x=flaty, mean=zero, cov=Pz, allow_singular=True)
  File "/usr/local/lib/python2.7/dist-packages/scipy/stats/_multivariate.py", line 473, in logpdf
    psd = _PSD(cov, allow_singular=allow_singular)
  File "/usr/local/lib/python2.7/dist-packages/scipy/stats/_multivariate.py", line 147, in __init__
    raise ValueError('the input matrix must be positive semidefinite')
ValueError: the input matrix must be positive semidefinite
```

I'm not certain yet if this is specific to my setup. Any thoughts?

**Comment by rlabbe** [comment]
Not sure why you set the mean to zero. The log-likelihood computes the (log of the) likelihood of the measurement matching the predicted state. 

In the UKF the predicted state is computed by the unscented transform, as is its covariance. Hence I suggest:

        # compute log likelihood
        mean = zp.flatten()
        flatz = np.asarray(z).flatten()

        self.log_likelihood = multivariate_normal.logpdf(
             flatz, mean, cov=Pz, allow_singular=True)

If you have code where you can usefully test this I'd appreciate your findings, but I am pretty sure it is correct. I have only given it 2 minutes thought, however.

**Pull request merged**
