### PR TITLE
update batch_mode to handle non constant matrices

### PR DESCRIPTION
**Pull request by bcordo**
This PR:

1. Adds non-constant F,H, and Q matrices to the batch filter
2. Adds non-constant F matrix to the rts smoother

Only for linear filters. 

Let me know if you want any changes.

### CODE REVIEW

**Comment by rlabbe** [comment]
Thank you for doing this. However, I cannot merge this as is. I'm happy to split up the work if you don't have time to tackle any/all of the below.

1. batch_filter has a side effect of altering self.F and self.Q. This, along with exceptions, can lead to the filter ending up in some unknown state.

one solution: save initial value of self.F and self.Q. Safely restore, even in the presence of exceptions.

I'm not convinced I like this, though. Probably`predict()` should accept an optional F and Q, since both matrices are allowed to be time varying. This would have the benefit of being more flexible and simplifying the logic of batch_filter. 

2. np.all(Rs ==None): I don't understand the intent of this construct. Why did you replace the `if Rs is None:` construct?

3. no unit tests.

4. Spacing in docstrings is not preserved/consistent with existing code.

5. Docstring for Fs, Hs and Qs is incorrect - each mentions self.R.

6. F is not an 'update' matrix as stated in the docstring. The term 'state transition matrix' is used elsewhere, and I'd like terminology to remain consistent. 

7. I wouldn't not merge due to this, but the function is still not maximally flexible. It does not work if you have an `u` input, or it you want to modify B dependent on time.

8. I wouldn't not merge because of this, but the signature of batch_filter is complex enough that an example is in order (yes, I know I didn't have an example either).

**Comment by bcordo** [comment]
Great thanks for the feedback. I'll keep iterating on this based on your points. And maybe it can get to a point for it to be useful for you. 

Brad

**Comment by bcordo** [comment]
Commit [fd1afd5](https://github.com/Censio/filterpy/commit/fd1afd55f3903f0857f84aecdbd29fce6d232110) addresses comments: 1., 3., 4., 5., 6., 7.

TODO:
2. unit tests. I wanted to push this before writing the unit tests in case you had feedback/changes/improvements.

**Comment by rlabbe** [comment]
Sorry, life overtook me for a bit, and I've neglected this. This looks good, and thank you so much for doing this.

**Pull request merged**
